name: dee_result
description: "A default result for Dart and Flutter"
version: 0.0.1
homepage: https://github.com/rkpontes/dee_result

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
